### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by yangzhiye** [tambetm/allenAI#1]
Could you  share me data that include 21298 questions？I need it to do  Graduation design，I‘am a chinese student. I missed the deadline. Thank you !!!!!  My email is  445922703@qq.com

**Comment by tambetm** [comment]
I saw you already asked the same question in Kaggle forum. Unfortunately I don't have the rights to distribute these questions, so you should refer to public questions on Allen AI homepage: http://allenai.org/data.html.
